### ISSUE TITLE
Bad Request with Jellyfin

### ISSUE THREAD

**Issue by Chuacheee** [Schaka/janitorr#101]
Hi, I have been using Janitorr for 1 year without any problem and I have had the famous problem of the connection with Jellyfin that I don't know how to solve.

I have version 10.10.3 of Jellyfin and 1.6.8 of Janitorr.

I read in other bugs that disabling the collections could work but unfortunately this has not been the case.

Can you please help me?

```
feign.FeignException$BadRequest: [400 Bad Request] during [GET] to [http://192.168.1.252:8096/Items?limit=10000&includeItemTypes=Series&parentId=1071671e7bffa0532e930debee501d2e&fields=Path&fields=ProviderIds&Recursive=true] [MediaServerClient#getAllTvShows(String)]: [Error processing request.]
	at feign.FeignException.clientErrorStatus(FeignException.java:222) ~[feign-core-13.1.jar:na]
	at feign.FeignException.errorStatus(FeignException.java:203) ~[feign-core-13.1.jar:na]
	at feign.FeignException.errorStatus(FeignException.java:194) ~[feign-core-13.1.jar:na]
	at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:103) ~[feign-core-13.1.jar:na]
	at feign.InvocationContext.decodeError(InvocationContext.java:126) ~[feign-core-13.1.jar:na]
	at feign.InvocationContext.proceed(InvocationContext.java:72) ~[feign-core-13.1.jar:na]
	at feign.ResponseHandler.handleResponse(ResponseHandler.java:63) ~[feign-core-13.1.jar:na]
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:114) ~[feign-core-13.1.jar:na]
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:70) ~[feign-core-13.1.jar:na]
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:99) ~[feign-core-13.1.jar:na]
	at jdk.proxy2/jdk.proxy2.$Proxy96.getAllTvShows(Unknown Source) ~[na:na]
	at com.github.schaka.janitorr.mediaserver.BaseMediaServerService.getTvLibrary(BaseMediaServerService.kt:105) ~[classes/:na]
	at com.github.schaka.janitorr.mediaserver.BaseMediaServerService.populateTvShowIds(BaseMediaServerService.kt:91) ~[classes/:na]
	at com.github.schaka.janitorr.mediaserver.BaseMediaServerService.populateMediaServerIds(BaseMediaServerService.kt:48) ~[classes/:na]
	at com.github.schaka.janitorr.jellystat.JellystatRestService.populateWatchHistory(JellystatRestService.kt:31) ~[classes/:na]
	at com.github.schaka.janitorr.cleanup.AbstractCleanupSchedule.cleanupMediaType(AbstractCleanupSchedule.kt:73) ~[classes/:na]
	at com.github.schaka.janitorr.cleanup.AbstractCleanupSchedule.scheduleDelete(AbstractCleanupSchedule.kt:50) ~[classes/:na]
	at com.github.schaka.janitorr.cleanup.AbstractCleanupSchedule.scheduleDelete$default(AbstractCleanupSchedule.kt:34) ~[classes/:na]
	at com.github.schaka.janitorr.cleanup.MediaCleanupSchedule.runSchedule(MediaCleanupSchedule.kt:56) ~[classes/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:359) ~[spring-aop-6.2.0-RC3.jar:6.2.0-RC3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.2.0-RC3.jar:6.2.0-RC3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.2.0-RC3.jar:6.2.0-RC3]
	at org.springframework.cache.interceptor.CacheInterceptor.lambda$invoke$0(CacheInterceptor.java:55) ~[spring-context-6.2.0-RC3.jar:6.2.0-RC3]
	at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:430) ~[spring-context-6.2.0-RC3.jar:6.2.0-RC3]
	at org.springframework.cache.interceptor.CacheAspectSupport.evaluate(CacheAspectSupport.java:565) ~[spring-context-6.2.0-RC3.jar:6.2.0-RC3]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:447) ~[spring-context-6.2.0-RC3.jar:6.2.0-RC3]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:409) ~[spring-context-6.2.0-RC3.jar:6.2.0-RC3]
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:65) ~[spring-context-6.2.0-RC3.jar:6.2.0-RC3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.2.0-RC3.jar:6.2.0-RC3]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:727) ~[spring-aop-6.2.0-RC3.jar:6.2.0-RC3]
	at com.github.schaka.janitorr.cleanup.MediaCleanupSchedule$$SpringCGLIB$$0.runSchedule(<generated>) ~[classes/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130) ~[spring-context-6.2.0-RC3.jar:6.2.0-RC3]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124) ~[spring-context-6.2.0-RC3.jar:6.2.0-RC3]
	at io.micrometer.observation.Observation.observe(Observation.java:499) ~[micrometer-observation-1.14.0-RC1.jar:1.14.0-RC1]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124) ~[spring-context-6.2.0-RC3.jar:6.2.0-RC3]
	at org.springframework.scheduling.config.Task$OutcomeTrackingRunnable.run(Task.java:83) ~[spring-context-6.2.0-RC3.jar:6.2.0-RC3]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.2.0-RC3.jar:6.2.0-RC3]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.VirtualThread.run(Unknown Source) ~[na:na]
```

**Comment by Schaka** [comment]
Can you find out which of your media libraries has the parentId `1071671e7bffa0532e930debee501d2e` in the URL when going through them? If any "real" collection has this id, there may be a bug we can fix here.

I think it's the same as in the other issue and requires a fix on Jellyfin's part.

**Comment by Chuacheee** [comment]
Nothing, no category URL contains that “parentID”, I used to have Janitorr libraries with older versions of Jellyfin and it worked fine but something happened in some Jellyfin update that stopped working.

I hope Jellyfin will fix it soon because Janitorr was a great add-on and the only solution I see is to downgrade Jellyfin.

In my case I have no collections, I have tried to do a clean install of Janitorr and it does not generate its folders, I understand it is because it does not connect.

I don't know if I can try an older version of Janitorr but I think this will not solve anything....

Greetings.

**Comment by Schaka** [comment]
You can disable Jellyfin and it will not create leaving soon connections but still delete media as expected.

I don't think that's a good solution. But I am also on the latest Janitorr and Jellyfin 10.10.3 without any of the issues you're seeing. 

What happens when you manually set your URL like this:
`https://jellyfin-url-here/web/#/list.html?parentId=1071671e7bffa0532e930debee501d2e`
`https://jellyfin-url-here/web/#/movies.html?parentId=1071671e7bffa0532e930debee501d2e`
`https://jellyfin-url-here/web/#/tv.html?parentId=1071671e7bffa0532e930debee501d2e`

Does anything show up?
I noticed Jellyfin now has URLs like `https://jellyfin-url-here/web/#/tv.html?topParentId=1071671e7bffa0532e930debee501d2e`, so it's possible something was changed here. If I can find the time, I'll have to investigate.

**Comment by Chuacheee** [comment]
Here are the results:

https://jellyfin-url-here/web/#/list.html?parentId=1071671e7bffa0532e930debee501d2e
**Result**: Nothing appears here.
https://jellyfin-url-here/web/#/movies.html?parentId=1071671e7bffa0532e930debee501d2e
**Result**: Here appears my movie library. 
https://jellyfin-url-here/web/#/tv.html?parentId=1071671e7bffa0532e930debee501d2e
**Result**: Here appears my series library.
https://jellyfin-url-here/web/#/tv.html?topParentId=1071671e7bffa0532e930debee501d2e
Result: Nothing loads either

I have noticed that since some time ago (but I can't tell you when) neither series nor movies appeared in the folders that Janitorr creates when you install it, but there have been deletions and the behavior has been the usual, except that neither movies nor series appeared in “leaving soon”.

I am not aware of how long this problem will take, maybe months and I just noticed it now.

For me Janitorr is indispensable so I prefer to keep it even if “leaving soon” does not appear in the interface, when connected to jellystat it does take into account if someone is watching the series, doesn't it?

I have also tried to recreate the API key without success, it seems that Janitorr does connect correctly with the other services: Jellystat, Jellyseer, Radarr, Sonarr, Bazaar.

If you need me to look at anything else, please do not hesitate to ask me.

**Comment by Schaka** [comment]
I don't fully understand the behavior you're seeing. You'll have to wait for me to debug this and probably just keep running running it as is. As long as both Jellyfin and Jellystat are enabled, it will account for viewing data.

However, if you disable Jellyfin, it cannot get th relevant data from Jellystat. I would need to completely disable leaving soon as an option to make it happen. You can disable leaving soon, by disabling file access or removing the `leaving-soon-dir` property. It should work for now.

It's super weird behavior you're seeing. If you have the time and patience, maybe run DBeaver on Jellyfin's SQLite database and figure out what collection is behind the id that's causing the error. 

For the record, Janitorr first calls
`GET /Library/MediaFolders`

Then it calls `/Items?limit=10000&includeItemTypes=Series&parentId=1071671e7bffa0532e930debee501d2e&fields=Path&fields=ProviderIds&Recursive=true` with each parentId being replaced with the IDs in the first call.

This should work (and it does on my server). Maybe you can reproduce this manually as well and see if something appears wrong for you and what it may be.

**Comment by Schaka** [comment]
The error you're seeing should still be appearing in the log. If you've changed nothing, then they should still appear.
It was always going to create the folders on your drive. But it *should* still create the leaving soon collections in Jellyfin.

Those are always created unless you turn them off via disabling file access or removing the leaving-soon folder in your yml entirely.

I suggest doing REST requests I recommended in my previous comment and seeing which ones lead to errors. Or more importantly, paste the JSON response for the first request here. 

It's referring to this request: https://api.jellyfin.org/#tag/Items

You should be able to see which parent has the ID that threw in error in your original post and we can go from there.

**Comment by Chuacheee** [comment]
Hi, here is my JSON, here is the exact extract of the ID that gave error in the log, I have done it with the help of chatgpt and using the command via ssh:

 wget -qO- --header=“X-Emby-Authorization: MediaBrowser Client=”Janitorr“, Device=”Docker“, DeviceId=”janitorr-docker“, Version=”1.6.8“, Token=”api-key“” http://192.168.1.252:8096/Library/MediaFolders

I hope it helps you, my technical knowledge is quite inferior to yours and there are things I can't quite understand.

```
{
  "Items": [
    {
      "Name": "Playlists",
      "ServerId": "31871457487d48c99caa4ded65855403",
      "Id": "1071671e7bffa0532e930debee501d2e", // parentId que causa el error
      "Etag": "f2f2ebed8f1e2dcc7f4bf8c6d042c7b8",
      "DateCreated": "0001-01-01T00:00:00.0000000Z",
      "CanDelete": false,
      "CanDownload": false,
      "SortName": "playlists",
      "ExternalUrls": [],
      "Path": "/config/data/playlists",
      "EnableMediaSourceDisplay": true,
      "ChannelId": null,
      "Taglines": [],
      "Genres": [],
      "RemoteTrailers": [],
      "ProviderIds": {},
      "IsFolder": true,
      "ParentId": "f27caa37e5142225cceded48f6553502",
      "Type": "ManualPlaylistsFolder",
      "People": [],
      "Studios": [],
      "GenreItems": [],
      "LocalTrailerCount": 0,
      "SpecialFeatureCount": 0,
      "DisplayPreferencesId": "acd905fc82f256d4facbd049e05d1b45",
      "Tags": [],
      "CollectionType": "playlists",
      "ImageTags": {},
      "BackdropImageTags": [],
      "ImageBlurHashes": {},
      "LocationType": "FileSystem",
      "MediaType": "Unknown",
      "LockedFields": [],
      "LockData": false
    },
}
```
I have seen that the error ID is the library called “playlists” and the parent id is: f27caa37e5142225cceded48f6553502, so I have executed this command:

wget -qO- --header=“X-Emby-Authorization: MediaBrowser Client=”Janitorr\“, Device=”Docker\“, DeviceId=”janitorr-docker\“, Version=”1.6.8\“, Token=”c698f534a8f8f456868b0dee81d8e5ff288\“”” http://192.168.1.252:8096/Items?parentId=f27caa37e5142225cceded48f6553502

The answer is all the playlists of all my libraries (or so I think) but I don't use any playlist in Jellyfin.

```
{
  "Items": [
    {
      "Name": "pelis",
      "ServerId": "31871457487d48c99caa4ded65855403",
      "Id": "20de6fee481d65b23cd2fc242282bd28",
      "ChannelId": null,
      "IsFolder": true,
      "Type": "Folder",
      "ImageTags": {},
      "BackdropImageTags": [],
      "ImageBlurHashes": {},
      "LocationType": "FileSystem",
      "MediaType": "Unknown"
    },
    {
      "Name": "pelis4k",
      "ServerId": "31871457487d48c99caa4ded65855403",
      "Id": "9a56534c2101bdb8af74477a9df789e0",
      "ChannelId": null,
      "IsFolder": true,
      "Type": "Folder",
      "ImageTags": {},
      "BackdropImageTags": [],
      "ImageBlurHashes": {},
      "LocationType": "FileSystem",
      "MediaType": "Unknown"
    },
    {
      "Name": "series4k",
      "ServerId": "31871457487d48c99caa4ded65855403",
      "Id": "62de9bfa5b2b22712aada315857cb05d",
      "ChannelId": null,
      "IsFolder": true,
      "Type": "Folder",
      "ImageTags": {},
      "BackdropImageTags": [],
      "ImageBlurHashes": {},
      "LocationType": "FileSystem",
      "MediaType": "Unknown"
    },
    {
      "Name": "series",
      "ServerId": "31871457487d48c99caa4ded65855403",
      "Id": "8010ca4a96e10e34facd80993a333521",
      "ChannelId": null,
      "IsFolder": true,
      "Type": "Folder",
      "ImageTags": {},
      "BackdropImageTags": [],
      "ImageBlurHashes": {},
      "LocationType": "FileSystem",
      "MediaType": "Unknown"
    },
    {
      "Name": "programas-tv",
      "ServerId": "31871457487d48c99caa4ded65855403",
      "Id": "5080a306eda9614bc1ecd94a39afcbca",
      "ChannelId": null,
      "IsFolder": true,
      "Type": "Folder",
      "ImageTags": {},
      "BackdropImageTags": [],
      "ImageBlurHashes": {},
      "LocationType": "FileSystem",
      "MediaType": "Unknown"
    },
    {
      "Name": "documentales",
      "ServerId": "31871457487d48c99caa4ded65855403",
      "Id": "904c9c3d176f7cb6f673b3a0d71668e5",
      "ChannelId": null,
      "IsFolder": true,
      "Type": "Folder",
      "ImageTags": {},
      "BackdropImageTags": [],
      "ImageBlurHashes": {},
      "LocationType": "FileSystem",
      "MediaType": "Unknown"
    },
    {
      "Name": "recordings",
      "ServerId": "31871457487d48c99caa4ded65855403",
      "Id": "b920252eeb829d609573b4e4b580af7d",
      "ChannelId": null,
      "IsFolder": true,
      "Type": "Folder",
      "ImageTags": {},
      "BackdropImageTags": [],
      "ImageBlurHashes": {},
      "LocationType": "FileSystem",
      "MediaType": "Unknown"
    }
  ],
  "TotalRecordCount": 7,
  "StartIndex": 0
}

```
If I put Janitorr in the same YML the error disappears except:
- It generates the physical folders but not virtual ones
- Healthcheck always appears “unhealthy”.

**Comment by Schaka** [comment]
That was helpful. It ended up being the wrong request, but the response should still help.

Please try the latest develop image when it's finished building. I now specifically filter out playlists. Hopefully this helps.

**Comment by Chuacheee** [comment]
Checked the :develop branch

It seems that the bug has been fixed and the behavior is as expected, glad to have been of help.

```
janitorr  | 
janitorr  |   .   ____          _            __ _ _
janitorr  |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
janitorr  | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
janitorr  |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
janitorr  |   '  |____| .__|_| |_|_| |_\__, | / / / /
janitorr  |  =========|_|==============|___/=/_/_/_/
janitorr  | 
janitorr  |  :: Spring Boot ::            (v3.4.0-RC1)
janitorr  | 
janitorr  | 2024-11-26T12:01:54.917+01:00  INFO 1 --- [           main] c.g.s.janitorr.JanitorrApplicationKt     : Starting JanitorrApplicationKt using Java 23.0.1 with PID 1 (/app/classes started by ubuntu in /)
janitorr  | 2024-11-26T12:01:54.923+01:00  INFO 1 --- [           main] c.g.s.janitorr.JanitorrApplicationKt     : No active profile set, falling back to 1 default profile: "default"
janitorr  | 2024-11-26T12:01:59.425+01:00  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8978 (http)
janitorr  | 2024-11-26T12:01:59.453+01:00  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
janitorr  | 2024-11-26T12:01:59.454+01:00  INFO 1 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.31]
janitorr  | 2024-11-26T12:01:59.565+01:00  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
janitorr  | 2024-11-26T12:01:59.566+01:00  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 4352 ms
janitorr  | 2024-11-26T12:02:01.742+01:00  INFO 1 --- [           main] c.g.s.j.config.RuntimeEnvironment        : Default charset UTF-8
janitorr  | 2024-11-26T12:02:01.744+01:00  INFO 1 --- [           main] c.g.s.j.config.RuntimeEnvironment        : sun.jnu.encoding UTF-8
janitorr  | 2024-11-26T12:02:01.748+01:00  INFO 1 --- [           main] c.g.s.j.config.RuntimeEnvironment        : sun.stdout.encoding null
janitorr  | 2024-11-26T12:02:01.748+01:00  INFO 1 --- [           main] c.g.s.j.config.RuntimeEnvironment        : sun.stderr.encoding null
janitorr  | 2024-11-26T12:02:01.748+01:00  INFO 1 --- [           main] c.g.s.j.config.RuntimeEnvironment        : ENV JAVA_TOOL_OPTIONS null
janitorr  | 2024-11-26T12:02:01.749+01:00  INFO 1 --- [           main] c.g.s.j.config.RuntimeEnvironment        : ENV LANG en_US.UTF-8
janitorr  | 2024-11-26T12:02:01.749+01:00  INFO 1 --- [           main] c.g.s.j.config.RuntimeEnvironment        : ENV LANGUAGE en_US:en
janitorr  | 2024-11-26T12:02:01.751+01:00  INFO 1 --- [           main] c.g.s.j.config.RuntimeEnvironment        : ENV LC_ALL en_US.UTF-8
janitorr  | 2024-11-26T12:02:03.393+01:00  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 8978 (http) with context path '/'
janitorr  | 2024-11-26T12:02:03.859+01:00  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8081 (http)
janitorr  | 2024-11-26T12:02:03.863+01:00  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
janitorr  | 2024-11-26T12:02:03.865+01:00  INFO 1 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.31]
janitorr  | 2024-11-26T12:02:03.907+01:00  INFO 1 --- [           main] o.a.c.c.C.[Tomcat-1].[localhost].[/]     : Initializing Spring embedded WebApplicationContext
janitorr  | 2024-11-26T12:02:03.913+01:00  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 505 ms
janitorr  | 2024-11-26T12:02:03.986+01:00  INFO 1 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 endpoint beneath base path ''
janitorr  | 2024-11-26T12:02:04.188+01:00  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 8081 (http) with context path '/'
janitorr  | 2024-11-26T12:02:04.235+01:00  INFO 1 --- [           main] c.g.s.janitorr.JanitorrApplicationKt     : Started JanitorrApplicationKt in 10.32 seconds (process running for 10.829)
janitorr  | 2024-11-26T12:02:08.900+01:00  INFO 1 --- [omcat-handler-0] o.a.c.c.C.[Tomcat-1].[localhost].[/]     : Initializing Spring DispatcherServlet 'dispatcherServletRegistration'
janitorr  | 2024-11-26T12:02:08.905+01:00  INFO 1 --- [omcat-handler-0] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServletRegistration'
janitorr  | 2024-11-26T12:02:08.907+01:00  INFO 1 --- [omcat-handler-0] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
janitorr  | 2024-11-26T12:02:18.966+01:00  INFO 1 --- [   scheduling-1] c.g.s.j.s.sonarr.SonarrRestService       : Treating TV shows as a whole - preparing to delete 0 shows
janitorr  | 2024-11-26T12:02:21.594+01:00  INFO 1 --- [   scheduling-1] c.g.s.j.cleanup.TagBasedCleanupSchedule  : Tag based cleanup disabled, do nothing
janitorr  | 2024-11-26T12:02:21.595+01:00  INFO 1 --- [   scheduling-1] c.g.s.j.c.WeeklyEpisodeCleanupSchedule   : Episode based cleanup disabled, do nothing
```

It creates the physical “leaving-soon” folders correctly in the expected directory, the only thing it doesn't generate are the virtual ones that appear in the Jellyfin library, but there is no strange error in the log.

I have tried to see the log of Jellyfin and Janitorr looking for the possible creation with the word “virtual”, “soon”, “deleted” and I have even created different users for the 1080p and 4k versions just in case it could affect the creation of virtual folders in Jellyfin.

```
jellyfin:
    enabled: true
    url: "http://192.168.1.252:8096"
    api-key: "774d87300e5b4b92b31db0e58c58b810"
    username: janitorr4k
    password: janitorr4k
    delete: true # Jellyfin setup is required for JellyStat. However, if you don't want Janitorr to send delete requests to the Jellyfin API, disable it here
    leaving-soon-tv: "Desaparece (series4k)"
    leaving-soon-movies: "Desaparece (peliculas4k)"
	
  jellyfin:
    enabled: true
    url: "http://192.168.1.252:8096"
    api-key: "c698f534a8f84568b0dee81d8e5ff288"
    username: janitorr
    password: janitorr
    delete: true # Jellyfin setup is required for JellyStat. However, if you don't want Janitorr to send delete requests to the Jellyfin API, disable it here
    leaving-soon-tv: "Desaparece (series)"
    leaving-soon-movies: "Desaparece (peliculas)"
```

Then I have activated the DEBUG mode but I don't see anything out of the ordinary...I have seen connections with Sonarr and Jellystat, I have seen how it looked at what the users had seen in the log, and everything seems to work correctly, but nowhere does it comment on the virtual folders generated by Janitorr.

I don't know if there is any way I can see if you have tried this connection or similar, or if I simply map the folders from Jellyfin and wait to see how it behaves.

But the good news is that the initial bug has been fixed.

**Comment by Chuacheee** [comment]
Ah ok, I didn't understand the process of generating the virtual folders, thanks for your help.

As a suggestion that may be a good idea, the advantage of the pre-creation of virtual folder, because allows to leave configured the cover image and texts for the virtual libraries and allows to leave the Janitorr configuration finalized since the initial installation, maybe is better for some users, is only a idea, I don´t know this technical difficulty.

If you want to close the ticket for me there is no problem, if it gives again some permissions error I quote this ticket #101 for your convenience.

Thanks for all and this great plugin.

**Comment by Schaka** [comment]
This is a different issue altogether.
It seems that your user Janitorr doesn't have permission to delete the media it tried to delete.
You can confirm this by manually trying to do it logged in as that user.

**Comment by Chuacheee** [comment]
I logged in with user Janitorr and deleted a complete movie and a series.

I can delete everything but “seasons” in Jellyfin, which is what Janitorr tried to delete in the log above.

However the episodes if they have been deleted, Jellyfin shows season 1 but empty of episodes, I cannot manually delete season 1 metadata with any admin user.

I have corrected based on your suggestion on how to configure application.yml, I didn't know how to configure 2 instances of Janitorr for correct operation.

I didn't know it was a different bug, sorry.

**Comment by Schaka** [comment]
If you cannot delete a season as your user, I would recommend you create a bug report with Jellyfin.
Maybe some of the files in that season have wrong permissions so that Jellyfin's container cannot delete them - but this is just a guess.

I'm closing this ticket then, as the bug is resolved. I cannot solve issues like Jellyfin's user not being able to delete a season, unfortunately.

If you do create that ticket with Jellyfin, please cross-reference it here. Thank you!
