### ISSUE TITLE
Add option to only delete files when free disk space reaches a threshold

### ISSUE THREAD

**Issue by majatocaha** [Schaka/janitorr#2]
I'd love to see that functionality, as sometimes no new media is added for a while, thus removing my need to delete existing files for that duration. Maybe optionally usable with a setting in application.yml?

Could be working like this:

Existing media:
A -> age 95 days, 10GB
B -> age 92 days, 20GB

Free disk space left is 5GB, Threshold for deletion is 10GB free disk space. Cleanup task would result in "A" being deleted, and "B" not being deleted, as the free disk space is now 15GB, which is higher than the threshold.

This way, media will only be deleted if it actually becomes necessary to expand free disk space.

**Comment by Schaka** [comment]
This is now available on develop and will be in the next release (1.0).

I decided against rechecking disk space after each delete. As Janitorr should run continously, I'm not too worried about micro optimizing.
