### ISSUE TITLE
Option to enable Jellystat for the entire show

### ISSUE THREAD

**Issue by Schaka** [Schaka/janitorr#25]
Currently, Jellystat works season by season.

It should be possible for the user to enable overwrite for the entire show, i.e. if one item of one season was watched recently, the entire show is treated as if it has been watched recently.

**Comment by ssamjh** [comment]
:+1:

**Comment by Schaka** [comment]
This is implemented on `:develop` as part of this feature: https://github.com/Schaka/janitorr/issues/37

I still want to make it possible to "save" an entire show by watching a single episode. Unfortunately, it's currently quite complicated to do with the way Janitorr is set up.

**Comment by Schaka** [comment]
In v1.4
