### ISSUE TITLE
Feature Request - Allow deletion of individual episodes and/or entire seasons

### ISSUE THREAD

**Issue by nothing2obvi** [Schaka/janitorr#28]
Hello, and thank you for this great service. I think it would be great to allow deletion of individual episodes and/or entire seasons. I have many daily shows that air for several months per season. For example, for one show, currently, Janitorr would have to wait at least until after the season is done in order to delete the season, which will contain 230 episodes by the end of the season. 

I would like to just keep the last 14 days worth of episodes, as an example.

Thank you for reading and for your time and effort. Just wanted to also say that the recent integration of Jellystat is a game-changer. Looking forward to your thoughts.

**Comment by Schaka** [comment]
I'll leave the ticket open. If there is enough interest, I might add this. But it goes against the way Janitorr is curently set up and would require quite a bit of effort. So don't hold your breath and don't expect it to ever become a feature.

You might be better off having a look at https://github.com/hrenard/cleanarr/ or a similar project

**Comment by nothing2obvi** [comment]
That's fair. Thanks for leaving it open. I hope more people find interest in this, then.

I took a look at deleterr but it appears to requires Plex and/or Tautulli. As I am in the Jellyfin ecosystem, this wouldn't work for me.

**Comment by hacshacdgacs** [comment]
Just adding that I have a couple shows I would appreciate something like this for as well for if it were to ever become a feature

**Comment by Schaka** [comment]
Would you guys be okay with this being tag based?

For example, you'd tag a show in sonarr "janitorr_daily" (assuming it's a daily or weekly release, or whatever).

Janitorr would then pick up those shows separately and delete by individual episodes, leaving only the last x days or last x episodes (either an option or executive decision by me). 

There would be no support for "Leaving Soon". I don't think it makes much sense for this use-case and would over-complicate things. Same with Jellyseerr overwriting the last watched dates.

Before I just jump into implementing this, I'd like some feedback. I currently have one or two shows this would apply to, so limited testing capabilities but also little interest myself.

**Comment by hacshacdgacs** [comment]
Yea, tag based works and makes sense for me

**Comment by nothing2obvi** [comment]
@Schaka Yes, tag based would work well for me!

**Comment by thereddestdog** [comment]
Emulating this project would be awesome: https://gitlab.com/spoatacus/sonarr-episode-trimmer/

**Comment by Schaka** [comment]
This is available on the `:develop` image now. Keep in mind that `develop` receives no native images.

**Comment by nothing2obvi** [comment]
Awesome! Will try it out. Thank you for working on this.

**Comment by Schaka** [comment]
Thank you. I need some feedback before this can be merged into the next official release.

**Comment by nothing2obvi** [comment]
Janitorr seems to be deleting my latest episodes. I'll provide more details when I get home in a few days, but I see in Sonarr that the latest episode is downloaded and then deleted.

**Comment by Schaka** [comment]
Definitely need a log file and your config.

My suspicion is your setup.

The code is fairly simple. It'll do all episodes if they exceed max age and then check if you have too many episodes and deletes the leftover. It's all in the TRACE logs.

**Comment by streamywave** [comment]
Hello, I have now activated the deletion of individual episodes. It seems to be working. The old episodes are being deleted. However, I have noticed that they are still being monitored. Is this intentional? If so, can this behavior be changed?

**Comment by streamywave** [comment]
My testcase is `WWE RAW`, a weekly running wrestling show. Each season contains all episodes of a year (aprox. 56 episodes). I have configured this series with Monitoring-Mode ´Future Episodes`. Can this maybe re-enable it again? Otherwise i dont have a third-party tool, which can activate something again. 

What do you mean with unmonitor the whole season? Does it specifically unmonitor the episode itself or only the whole season, when no episodes are left?
