### ISSUE TITLE
2 radarr instances ¿its possible?

### ISSUE THREAD

**Issue by Sergiomg86** [Schaka/janitorr#31]
Thank you for your plugin, I just installed it and it seems to be correct.

I have created an installation of radarr4k and added it to aplications.yml.

It seems that the plugin has started again without problems adding this new client.

Janitorr can work with two radarr clients to differentiate 4k from 1080p?

**Comment by Schaka** [comment]
No, at this point you'll have to set up a second instance for a second instance of Radarr.
I have no intention of making this possible.

The native image has an extremely low footprint both for memory (50MB) and CPU, you can easily spin up a second container for Janitorr. That's the magic of Docker.

**Comment by Sergiomg86** [comment]
Thanks for your help

Ok, in the current container I have all the connected software in application.yml:

sonarr
radarr
jellyfin
jellyseer
jellystat

In the new janitorr docker I understand that not everything is necessary, I understand that in the new configuration of application.yml it is fine with:

jellyfin
radarr (4k version)

Do I also add jellyseer and jellystat in the duplicate janitorr container?

**Comment by Schaka** [comment]
You will have to duplicate everything you need.
If you care about viewing stats, you need to connect Jellyfin and Jellystat as well (Jellystat depends on Jellyfin).

Keep in mind:
- Jellyfin will delete media, so if something is available in Jellyfin and it gets the info that it was deleted from Radarr, it will find the movie in Jellyfin and delete it (this, I can probably make optional)
- Jellyseerr works by request, but can't really differentiate between a request to one Radarr instance or another on Janitorr's side, so it WILL delete the request if media matches


If that's fine by you, you can set it up.
My takeaways from this, for people with multi setup:
- make deletion via Jellyfin into an option
- build in Jellyseerr support for matching the Radarr and Sonarr instance

**Comment by Schaka** [comment]
I implemented support for multiple servers so the wrong request is not deleted for Jellyseerr on the develop branch. You can test is using the `:develop` image if you want. I have limited testing capabilities and will not push it to prod until I feel comfortable with it.

**Comment by Sergiomg86** [comment]
In the end I will wait because my 4k library is going to be very short and I made a simple shell to delete the media after 30 days
