### ISSUE TITLE
Not creating leaving-soon directories

### ISSUE THREAD

**Issue by sjafferali** [Schaka/janitorr#36]
I just updated and after doing so, the leaving-soon directories do not seem to be getting created when from-scratch is set to true in the configuration.

**Comment by Schaka** [comment]
Can so upload a log with trace enabled?

It's likely you're lacking file permissions or didn't update your application.yml correctly so that currently, no leaving-soon links are created.

When I released 1.0 a while ago, deletion times were mapped onto disk space remaining percentages.

**Comment by sjafferali** [comment]
[janitorr_logs.txt](https://github.com/Schaka/janitorr/files/15031516/janitorr_logs.txt)
[application.txt](https://github.com/Schaka/janitorr/files/15031525/application.txt)

My configuration and logs attached. The application.yml file was renamed to application.txt so github would let me upload it.

**Comment by Schaka** [comment]
Everything looks correct to me. I have a theory what could be the problem though. It's possible that the second call with an empty list would clean up all leaving-soon links. 

Can you please try the latest `:develop` image? 

PS I'm going to email you to your GitHub reqistered mail for commits.

**Comment by sjafferali** [comment]
> Everything looks correct to me. I have a theory what could be the problem though. It's possible that the second call with an empty list would clean up all leaving-soon links. Can you please try the latest :develop image?

Seems like you are right. I just tested the develop image and links are being created using that version as expected.

**Comment by Schaka** [comment]
Great, I'll push out a new release. Thanks for reporting!
