### ISSUE TITLE
Feature Request - Delete entire show as an option

### ISSUE THREAD

**Issue by hacshacdgacs** [Schaka/janitorr#37]
Is there any way to allow Janitorr to delete an entire show instead of just going season by season? 

The way I have my sonarr setup currently is that if  a show is no longer monitored it loses the 'keep' tag. Personally I'm not a fan of only having select seasons of a show so having the seasons disappearing based on age makes my library feel incomplete. 

(I know I could always just delete the show myself when the seasons start disappearing or deleting it early but I like the idea of having it automated and clearing up space on it's own).

**Comment by Schaka** [comment]
I'll consider it. It currently goes against the idea of Janitorr - I really do treat every season like it's only entity because that's how I manage my library.

How would you determine when the show needs to be deleted? When any single episode expires it takes the show with it? Regardless of the oldest or most recent season?

If you can think this feature through a little more, I may be able to implement it. There are people wanting single episode deletion too, so it's a bunch of cases that need to be considered at all times.

**Comment by hacshacdgacs** [comment]
I think I'd personally prefer for it to be the latest episode/season to
expire, it saves the risk of a show being deleted immediately after
becoming unmonitored in my case (which if I wanted to happen I would just
delete it myself).

**Comment by Schaka** [comment]
That's good enough of a layout for me and I'll see what I can do about it.

No promises, but it'll go on the roadmap.

Does jellystat not work with Emby? I could swear I had seen that it does. It might be worth setting it up for you and just seeing what sticks. The API between the two hasn't grown far enough apart to warrant significant changes.

Implementing Emby for Janitorr took me a day, but I'm obviously only using a tiny part of the API.

**Comment by hacshacdgacs** [comment]
Sweet, thank you.
Last time I tried Jellystat it didn't work for me (at least I don't remember it working) and there is an open issue/request for emby support that's in the roadmap an update or two down the line but I'll give it another go later today anyway.

**Comment by Schaka** [comment]
I have implemented a basic version, which is available in the `:develop` image. Currently having limited testing capabilities, please feel free to give it a shot and report back.

If you're currently using the `:native` image, keep in mind that the `application.yml` file needs to be mapped differently.

**Comment by hacshacdgacs** [comment]
I'm currently busy over the next couple of days but will test when I'm
able. Thank you

**Comment by Schaka** [comment]
Do all of these have a history?

I added some trace logging in the latest build. Might be worth uploading a full trace log here.

Here is how it should work:
- history is grabbed for each season in a TV show, just like usual
- at the end, we interpret the history for the whole show and update each season's date with the most recent grab in the entire show's history
- each season is handled separately, but all seasons contain the same parameters

The leaving-soon collection uses the same date info as the deletion component itself. If you let it re-create your leaving soon folder, are some seasons still missing? I suspect it's old data that wasn't cleaned up, maybe?

**Comment by hacshacdgacs** [comment]
These shows all have history and I deleted my folder so it was able to
rebuild and repopulate on its own. The same things happened. I'll have a
look at the log later when back at home

**Comment by Schaka** [comment]
Then it *should* work. I'll need a full log with trace logging enabled. 

The log to look out for specifically, is this one:
```
log.trace("Treat TV show as a whole - overwriting season import date - IMDB: ${libItem.imdbId} imported at $latestDate")
```

In the limited testing I was able to do, it seemed to work just fine for me. Granted, everything requires each season to have a grab history with `downloadFolderImported` entries.  

It would look a little something like this:
![image](https://github.com/Schaka/janitorr/assets/2223171/4ab6d65b-b053-4880-aecc-60c061c6fa21)

If you click on your history in Sonarr for every season, it should show this. The **only** way this could be overwritten is if Janitorr detects that the history is outdated and Sonarr currently contains NO files for this season at all. It will then be disregarded entirely - can't create symlinks or delete files where there aren't any.

**Comment by hacshacdgacs** [comment]
All the shows and seasons definitely have history linked for them. I'm unable to find that line in my logs. I've enabled them by adding Trace:True in my environment variables, is there another way I should have done this?

**Comment by hacshacdgacs** [comment]
Okay, I've found those lines in the trace logs so everything appears to be working. It's possible that sonarr managed to import a multi-season pack even though it wasn't meant to so isn't tracking everything properly. The feature does work properly however, thank you.
