### ISSUE TITLE
Free Space No Longer Shown When Items Added To Leaving Soon Collections

### ISSUE THREAD

**Issue by hacshacdgacs** [Schaka/janitorr#41]
Not an issue but more a question. 
When the deleted soon collection has been created and items have been added to it I'm no longer seeing a free space percentage in the logs, is this normal behaviour? It used to show how much space was available an personally I'd like it to keep showing that if I could.
![image](https://github.com/Schaka/janitorr/assets/85550264/8fe0eb82-5c91-4d25-8ea3-62bf8f9d34bb)

**Comment by Schaka** [comment]
The percentage is only logged if a cleanup condition is met and file system access is given (required to read disk space).

You can find the respective code in AbstractCleanupSchedule and MediaBasedCleanupSchedule.

Feel free to fork and adjust for yourself, you can easily manipulate the build up spit out an image for you without even being able to build the project locally.
