### ISSUE TITLE
Jellystat question: Does watching media in leaving soon get monitored as if it were watched in its normal library?

### ISSUE THREAD

**Issue by hacshacdgacs** [Schaka/janitorr#45]
Now that jellystat works with emby I have a question regarding the leaving soon libraries. 
If someone were to watch a movie that's in leaving soon would it then be removed from leaving-soon as jellystat has recognised it's been seen? Do I need to have it set that Jellystat also monitors the leaving soon libraries for this to work or do I only need to monitor the normal libraries?

**Comment by Schaka** [comment]
Jellystat monitors all libraries by default. But yes, if you want it to catch someone watching it via Leaving Soon, it needs to have the view history. 

Since the leaving soon directories aren't deleted, they won't disappear from leaving soon unless you use the from-scratch option.

**Comment by bonswouar** [comment]
Do you confirm it should (still) work?

The last movies that have been watched from Leaving Soon directory (as shown in Jellystat) don't seem to be "reset", they're still in Leaving Soon. 
Plus I can see in the logs one of them is to be deleted (but won't because it's seeding), that seems to confirm the watch date hasn't been updated

_I have from-scratch enabled, and the library is tracked in Jellystat_

**Comment by Schaka** [comment]
Does Jellystat have info about THAT season being watched, or that movie?

I have a suspicion what could cause it to miss this. 
Right now, we're matching Jellyfin media ids (those uuid you can see in the URL using Jellyfin) and then requests view stats via Jellystat. Now if they were different between leaving-soon and your main library, this could be an issue.

I thought they were the same, but they might be truly unique to their path on disk not to the media they contain.
This is fixable and I'll get it sorted.

**Comment by bonswouar** [comment]
Checking at the URL I confirm the `id` is different

Thanks!!

**Comment by Schaka** [comment]
There's a potential fix in the next develop image. It'll take a while to get built, but you can use the `native-amd64-develop` tag 10 minutes from this response and report back whether that solves your issue.

**Comment by bonswouar** [comment]
The develop images fails with the error:
> janitorr  | Failed to bind properties under 'application' to com.github.schaka.janitorr.config.ApplicationProperties:
janitorr  |     Reason: java.lang.NullPointerException: Parameter specified as non-null is null: method com.github.schaka.janitorr.config.ApplicationProperties.<init>, parameter mediaDeletion

**Comment by Schaka** [comment]
Were you not using the native image before?
If you were using native, it's `native-amd64-develop`.

If you weren't, it's just `develop`.

The error is related to your `application.yml` not being mapped correctly, this happens if you switch between images as they're mapped differently.

**Comment by bonswouar** [comment]
> Were you not using the native image before?

I wasn't! I originally didn't feel concerned by "If you restart more often than once a week or have a very low powered server, this is now recommended", my bad!
I've just updated the volumes, native develop image runs fine now

Unfortunately it seems the fix doesn't work: same logs, and Leaving Soon still contains recently watched movies

**Comment by bonswouar** [comment]
I might not post the full logs here, but I've noticed there's apparently no "Updating history" trace log for Movies in Leaving Soon directory

There's even a movie that I've watch a long time ago, but has been watched from Leaving Soon multiple times since (including by me), and the Updating History only refers to the old date from the main movie folder.

And I've checked multiple times in Jellystat just to be sure, the watch history is correct there

**Comment by Schaka** [comment]
I'll have to do some debugging and see what's wrong. It should be able to find all matches now. Media server ID refers to the ID it's given by Jellyfin, the one in the URL that's different between the two.

Out of all the entries for watched dates it finds, it would then use the most recent between all watches across all libraries.

It's possible I'm an idiot and have been using the oldest date. But it should be correct.

**Comment by bonswouar** [comment]
I see, so `mediaServerId` is not server Id, but media ID on server ; that was a bit confusing my bad 😄 

>It's possible I'm an idiot and have been using the oldest date. But it should be correct.

I don't think that's the issue, as the movies that haven't been watched except in Leaving Soon don't appear at all in Updating history logs

Let me know if you need more tests or something (if you need full logs I can send them on Matrix or whatever)

**Comment by Schaka** [comment]
If you're able to, call Jellystat's `/getItemHistory` endpoint and pass the jellyfin ID you see in your leaving soon collection.

If this returns the correct info, then I've made a mistake somewhere that I'll have to find.

**Comment by bonswouar** [comment]
I've just checked and yes, Jellystat's api does seem to return the correct info with IDs from Leaving Soon

**Comment by Schaka** [comment]
Are you using Emby? I think I may know what the issue could be.
When going through libraries to identify which ones to consider for filtering, there are a few calls that I'm not too sure Emby may handle slightly differently (even though both servers do respond to them).

**Comment by bonswouar** [comment]
I'm not using Emby, only Jellyfin

But I've just tried the latest develop image and it seems to work now! `Updating history` logs seems right for those movies, and the symlinks for watched ones have been correctly removed

Thank you for looking into this issue!

**Comment by Schaka** [comment]
Great, glad it was resovled. Here's to hoping it'll continue to work for Emby. I didn't change the endpoints and they were functional before, so here's to hoping.

**Comment by hacshacdgacs** [comment]
Can confirm Emby still works fine on the latest develop version with the
leaving soon collections
