### ISSUE TITLE
Jellystat is looking only for movies history, not for shows

### ISSUE THREAD

**Issue by Eldarock** [Schaka/janitorr#50]
Hello ! First : Thanks for this software, really useful !

Next : 

I tried to configure the application, and everything was looking good, except one thing :
One show was set to be deleted, but i knew that i watch at this show some days ago, so i dig a bit.

Jellyfin, Jellyseer, Jellystat all activated and setup correctly. 
Debug mode showed me that janitor access to Jellystat and update history correctly but... only for movies.
Shows are fine, but no trace of jellystat in logs, only sonarr/Jellyseer, so some recently watched show are marked as to be deleted.

Is that a bug, or is that a hidden settings for that somewhere that i missed ?

**Comment by Schaka** [comment]
Are you sure you watched THAT season?
There's currently [a feature](https://github.com/Schaka/janitorr/issues/37) only available on the develop branch that makes it possible to have a single episode reset the timer for the entire show (in JellyStat support).

By default, it will delete it season by season and you need to have seen an episode of the season you're looking at.

Otherwise as per usual, attach a log file and your config (redact sensible info).

**Comment by Eldarock** [comment]
Yup, sure.

Looks at this jellystat history :

HPI was watched, season 1 and 2 like 3 weeks ago.
![image](https://github.com/user-attachments/assets/0111eae1-1f29-4a47-a9a6-ff21dc62ffd8)

But Janitor deleted this seasons.
Maybe it's because of the language of the show ? Jellystat shows me in french, and sonarr shows me the english title.
Obviously i didn't save the logs, but i can try to replicate the error if you want to.

**Comment by Schaka** [comment]
If you can, please get me a log file with trace logging.
I use IMDB, TMDB and TVDB IDs to match media in Jellystat with Sonarr, depending on what's available. 

So if it can find a match, it should say so. 
It's going to log any watch history it finds for a matched TV show/season. It should give you enough insight to see if it generally works or not.

**Comment by Schaka** [comment]
You misunderstand the logs. 

Look at the very first line. I only kept the rest in for clarity, since these aren't DEBUG or TRACE logs.
After watching 2 minutes of the first episode of season 2 of the first show mentioned in the above, it doesn't appear anymore.

This is because Janitorr decided it is now out of the window that it would need to be in to expire.

**Comment by Eldarock** [comment]
Another example that i tried this morning : 
![image](https://github.com/user-attachments/assets/b7a7fbe7-5d8f-4316-af7c-f066694f001d)
Shows last watched less than 3 month ago

config setted : 

`season-expiration:
      5: 180d
      20: 180d # 6 months`

Logs : 

`2024-08-08T10:30:37.046-04:00  INFO 1 --- [           main] c.g.s.janitorr.JanitorrApplicationKt     : Started JanitorrApplicationKt in 0.247 seconds (process running for 0.272)
2024-08-08T10:30:54.199-04:00 TRACE 1 --- [   scheduling-1] c.g.s.j.mediaserver.MediaServerService   : Season folder - Source: /mnt/user/shows/The Good Doctor (2017)/Season 06, Target: /mnt/user/leaving-soon/tv/media/The Good Doctor (2017)/Season 06
2024-08-08T10:30:54.199-04:00 TRACE 1 --- [   scheduling-1] c.g.s.j.mediaserver.MediaServerService   : Creating season folder /mnt/user/leaving-soon/tv/media/The Good Doctor (2017)/Season 06
2024-08-08T10:30:54.200-04:00 DEBUG 1 --- [   scheduling-1] c.g.s.j.mediaserver.MediaServerService   : Creating episode link from /mnt/user/shows/The Good Doctor (2017)/Season 06/The Good Doctor (2017) - S06E10 - Quiet and Loud.mkv to /mnt/user/leaving-soon/tv/media/The Good Doctor (2017)/Season 06/The Good Doctor (2017) - S06E10 - Quiet and Loud.mkv
2024-08-08T10:30:54.236-04:00  INFO 1 --- [   scheduling-1] c.g.s.j.s.sonarr.SonarrRestService       : Dry run - not deleting any TV shows without files or monitoring
2024-08-08T10:30:56.285-04:00 DEBUG 1 --- [   scheduling-1] c.g.s.j.jellystat.JellystatRestService   : Updating history - user Thomas watched Le Monde de Nemo at 2024-06-29T19:44:36.270Z
2024-08-08T10:30:58.194-04:00  INFO 1 --- [   scheduling-1] c.g.s.j.cleanup.TagBasedCleanupSchedule  : Tag based cleanup disabled, do nothing
2024-08-08T10:30:58.194-04:00  INFO 1 --- [   scheduling-1] c.g.s.j.c.WeeklyEpisodeCleanupSchedule   : Episode based cleanup disabled, do nothing`

I don't paste all the jellystat updating history, but there are all related to movies, not shows.
Maybe i don't understand something ?

**Comment by Schaka** [comment]
Was that show (in the example) watcher longer than 60s econds?
From your logs and your config, I can't tell much. It's a bit limited. 

In Jellyfin, when you check the meta data for the good doctor (season 06) does it contain any IMDB, TMDB, etc?

Jellystat uses [one simple function](https://github.com/Schaka/janitorr/blob/develop/src/main/kotlin/com/github/schaka/janitorr/jellystat/JellystatRestService.kt#L27). It gets the id of the show/season from Jellyfin first and then searches its own watch history. 

If it finds season 6 in your example, it would log that it found it. It's possible individual seasons do not have the correct meta data or ID in Jellyfin. If you active the whole-show flg, it would not go season by season. 

This is more likely than not missing data on your end somehow.

**Comment by Eldarock** [comment]
Episode was watched entirely

Metadata in jellyfin for this episode :
imdb : tt23727902
tvdbId : 9472624

Metadata for this season in jellyfin : 
TheTVDB Season Id
2006665

**Comment by Schaka** [comment]
So the matching works as follows:
- find show at Sonarr, remember metadata (imdb, tmdb, tvdb)
- get all items from Jellyfin that are visible and in a collection type Series
- if "whole-show" is not activated, go through every show found in Jellyfin, go into each season and remember them individually (with their Jellyfin ID that looks like `c832ace18793151d715f45ebdd135bd6&serverId=ba136f1bd03e473b8cedfcf910527b30` in your URL
- match the show/season - either if IMDB, TMDB or TVDB (for the whole show) to the entry found in Sonarr
- take that Jellyfin ID mentioned before and search Jellystat to see if it has a watch history

For me, this works perfectly. I just ran everything again with TRACE logging on my server and can't see any problems.

If your debugging logging fails to show any watch history, it's because it couldn't match anything to the Jellyfin ID it found. 

I added some more trace logging in the latest `:develop` image. Feel free to use that.

**Comment by Eldarock** [comment]
I will continue to debug with the new traces logs as soon as it's available the native image.
Thanks a lot again for your time, really appreciated.

**Comment by Schaka** [comment]
You can try this via `:native-develop` now.

**Comment by Eldarock** [comment]
Looks like if i let janitorr check for the season and not the whole show, the search is not working :

The imdb is not null here, so i don't really understand where the problem is now, because it's working if i set the whole-show option to true : 

`2024-08-09T08:37:40.242-04:00 TRACE 1 --- [   scheduling-1] c.g.s.j.jellystat.JellystatRestService   : Could not find any matching media server id for /mnt/user/shows/The Good Doctor (2017)/Season 06/The Good Doctor (2017) - S06E01 - Afterparty.mkv IMDB: tt6470478 TMDB: null TVDB: 328634 Season: 6`

**Comment by Schaka** [comment]
If you look at the full show in Jellyfin, what's the meta data? Does it match what it shows in the log? Is it in a library that is of type Series?

The [check for season](https://github.com/Schaka/janitorr/blob/develop/src/main/kotlin/com/github/schaka/janitorr/mediaserver/AbstractMediaServerRestService.kt#L152)s checks that:
- the type in Jellyfin is "Season"
- the name contains "Season"
- the number matches, based off the name

I noticed you use Spanish (?) as your Jellyfin language. It's possible that I have a language requirement in my code my accident. 
Could you please set the language in the profile of your Janitorr user to English and see if that fixes it? If it does, I have to try and rework my matching logic. Granted, it may be related to server language, not client language.

If you go to the season page in Jellyfin, it should show something like this:
![image](https://github.com/user-attachments/assets/0bbbbcd5-2baf-47a4-b077-e78b6b7a5d1b)


What does it look like for you?

I was hoping the Name returned by [this call](https://api.jellyfin.org/#tag/TvShows/operation/GetSeasons) in Jellyfin would not be localized for seasons.

**Comment by Eldarock** [comment]
Yup, the metadata are correct for the full show, that's why i think when the whole-show is enabled, the match works.
for debugging purpose, all show imdbId : tt6470478, the same we saw in the log in my preivous message.

I'm using french fyi, i setted the language for the janitorr user to english, without success.

But i found why with your code snippet : 

`val seasonMatches = candidate.Type == "Season"
                && candidate.Name.contains("Season")`

In french, it looks like that :                 
![image](https://github.com/user-attachments/assets/4c545be6-c874-4df7-bf23-cc02cbff90d9)

If i change it to "Season 6" instead, the check is working good for this season.
Maybe you can check if the season number is not empty instead ? it will works for all language i think, but i don't know if there will be side effects.

**Comment by Schaka** [comment]
You may try again. I made it language agnostic, by assuming it's always "word <number>".

The right way would be to read the local from Jellyfin/Emby and then get the correct word for "Season" from the Jellyfin translation, but for now that's more work than I'm willing to do. It's gone on the TODO list.

**Comment by Eldarock** [comment]
Yeah, looking good now for the french saison title.

BUT (and i'm sorry for bad news), some tv show don't have "Season X" has title.
I have multiple examples :

True Detective Season 4, have title : "Night Country"
All the Bridgerton season have a different title than "Season X"

tested with tvdb, and themoviedb metadata fetcher.

I got some others show who have the same issue, but it's a minority now, the language issue is gone.
But i think you don't want to check the title, but if it's a season "class", if there is a season number and a not empty title maybe ?

**Comment by Schaka** [comment]
Can you post some example of what those seasons look like in Jellyfin? Is your season folder on your hard drive called Season 03 or Night Country in this example?

My biggest problem is that a number exists in Sonarr and I need to match that number to what exists in Jellyfin/Emby.

And no worries. I'm happy to help if someone reports a bug that hasn't happened in my case.
I would highly recommend you adjust the naming structure for your files according to [TRaSH Guides](https://trash-guides.info/Sonarr/Sonarr-recommended-naming-scheme/) if you haven't done so yet.

**Comment by Eldarock** [comment]
I'm already using TraSH guides yep.

Path on drive is : shows/True Detective (2014)/Season 04
Metadata in Jellyfin :
![image](https://github.com/user-attachments/assets/5951751c-fade-4bb2-b68f-2c07797fde09)

**Comment by Schaka** [comment]
Thank you. It seems Jellyfin uses the index and shows it as "Season number" in the meta data editor.

I adjust it to where I now also use the index as a backup. You can test it again.

This will also be in the next release.

**Comment by Eldarock** [comment]
It's looks perfect now. No more unmatched show/seasons with the latest native version :)
Issue can be closed i think.
Good work !

**Comment by Mavyre** [comment]
> So the matching works as follows:
> 
> * find show at Sonarr, remember metadata (imdb, tmdb, tvdb)
> * get all items from Jellyfin that are visible and in a collection type Series
> * if "whole-show" is not activated, go through every show found in Jellyfin, go into each season and remember them individually (with their Jellyfin ID that looks like `c832ace18793151d715f45ebdd135bd6&serverId=ba136f1bd03e473b8cedfcf910527b30` in your URL
> * match the show/season - either if IMDB, TMDB or TVDB (for the whole show) to the entry found in Sonarr
> * take that Jellyfin ID mentioned before and search Jellystat to see if it has a watch history
> 
> For me, this works perfectly. I just ran everything again with TRACE logging on my server and can't see any problems.
> 
> If your debugging logging fails to show any watch history, it's because it couldn't match anything to the Jellyfin ID it found.
> 
> I added some more trace logging in the latest `:develop` image. Feel free to use that.

Makes sense. However, on my Jellyfin instance, only the tvdb is available to edit for season, which is a bit weird...  Can't find out to match everything
