### ISSUE TITLE
Feature request: ability to remove unwatched requests (Jellystat+Jellyseerr)

### ISSUE THREAD

**Issue by anthonymag** [Schaka/janitorr#54]
One manual cleanup I still periodically find myself doing is stuff people requested but never watched. 

I'd love the ability to auto clean these after x amount of time. 

Would this be possible with Jellystat combined with Jellyseerr? 
Alternatively, since Jellyseerr supports tagging requested content, a special deletion rule for watch count on certain tags could satisfy the same goal. 

Thanks for the work on this handy tool!

**Comment by anthonymag** [comment]
Right so at the moment it will clean up content when disk space hits a threshold I set, and it works great. This is similar, but it would be a special treatment of **requested** content since it would help proactively avoid getting to that space threshold. It can also help to encourage Jellyseerr users to watch what they request in my case.

**Comment by Schaka** [comment]
Then just run it with disk space set to 100%. 

I don't see the need for this feature at all. You can even use the tag based cleanup for that specifically.

**Comment by anthonymag** [comment]
Interesting. I'll try that out. Thanks!
