### ISSUE TITLE
Feature Request: Option to configure name of created collections

### ISSUE THREAD

**Issue by Eldarock** [Schaka/janitorr#60]
Hello !

First of all : thanks for your work, again :)
I think it can be a good thing to configure the name of the generated collections.
It will allow you to have a jellyfin homepage in the same language, instead of having mix of native language and english.

**Comment by Schaka** [comment]
You can try the latest develop image.
You'll find the config template here: https://github.com/Schaka/janitorr/blob/develop/src/main/resources/application-template.yml

**Comment by Eldarock** [comment]
It's working perfectly. Thanks a lot Sir.
Is there any place i can "tip" you a coffee ?
