### ISSUE TITLE
[feature-request] Being able to configure how to treat upgraded episodes

### ISSUE THREAD

**Issue by tgudlek** [Schaka/janitorr#62]
Hey!

I'm setting a really long target expiry window (400d), and also treat series as a whole.
Additionally, my quality profiles are pretty aggressive with updating, which means the chance of not getting an episode updated in 400d is not that high -- this then also means the whole series will get "refreshed" if a single episode gets updated in 400d due to:

```
If any of your quality profiles allow for updates, it will consider the most recent download when calculating its age.
```

Any chance you could expose configuring this as a strategy? I'd prefer to treat the first time I've grabbed an episode when calculating its age.

**Comment by Schaka** [comment]
Are you sure that's going to be beneficial?
Sonarr keeps your grab history. So if the same show ever gets grabbed again, it'll instantly be up for deletion.

Only if the entire show gets removed, is the history also gone. 

Should now be available for develop image.

**Comment by Schaka** [comment]
Please report back if this suits your requirements and I'll be able to close this.
