### ISSUE TITLE
Logs show unsupported CPU

### ISSUE THREAD

**Issue by rickardfransson** [Schaka/janitorr#63]
Hi! Just got janitorr installed. Using dry.run. And wanted to have a look what will be deleted.
Took docker logs janitorr and got this fault:

`rickardfransson@Rickardfransson:~/opt/janitorr$ docker logs janitorr
permission denied while trying to connect to the Docker daemon socket at unix://                                                                                                             /var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.46/containers/ja                                                                                                             nitorr/json": dial unix /var/run/docker.sock: connect: permission denied
rickardfransson@Rickardfransson:~/opt/janitorr$ sudo docker logs janitorr
The current machine does not support all of the following CPU features that are                                                                                                              required by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SS                                                                                                             E4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA].
Please rebuild the executable with an appropriate setting of the -march option.T                                                                                                             he current machine does not support all of the following CPU features that are r                                                                                                             equired by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE                                                                                                             4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA].
Please rebuild the executable with an appropriate setting of the -march option.T                                                                                                             he current machine does not support all of the following CPU features that are r                                                                                                             equired by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE                                                                                                             4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA].
Please rebuild the executable with an appropriate setting of the -march option.T                                                                                                             he current machine does not support all of the following CPU features that are r                                                                                                             equired by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE                                                                                                             4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA].
Please rebuild the executable with an appropriate setting of the -march option.T                                                                                                             he current machine does not support all of the following CPU features that are r                                                                                                             equired by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE                                                                                                             4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA].
Please rebuild the executable with an appropriate setting of the -march option.T                                                                                                             he current machine does not support all of the following CPU features that are r                                                                                                             equired by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE                                                                                                             4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA].
Please rebuild the executable with an appropriate setting of the -march option.T                                                                                                             he current machine does not support all of the following CPU features that are r                                                                                                             equired by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE                                                                                                             4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA].
Please rebuild the executable with an appropriate setting of the -march option.r`

What to do?

**Comment by rickardfransson** [comment]
![image](https://github.com/user-attachments/assets/500cc4a2-b1b6-4a78-b548-df3f4ff5950f)

**Comment by rickardfransson** [comment]
So, i have tried native/stable/develop branch, but all ends with same result.

**Comment by Schaka** [comment]
What CPU do you have? The stable and develop images are available for arm64 and amd64. 
The native images are x86 only (no arm support).

This is either a permission issue on your system where Docker can't read CPU info correctly (permission denied errors at the start) or your CPU doesn't support the feature set required. AVX2 is not available on CPUs older than 4th gen Intel or first gen Ryzen.

It's possible I could build a native image for other architectures, but I'm not really interested. I would rather fix this via the good old Java image. So if you could kindly get me the error with the stable image, that would help a lot.

You can see here clearly that the stable image is available as arm64:
https://github.com/Schaka/janitorr/pkgs/container/janitorr/265313449?tag=stable

**Comment by rickardfransson** [comment]
This is my cpu
![image](https://github.com/user-attachments/assets/11695356-7da3-46c1-a4d4-51678e090d62)

**Comment by Schaka** [comment]
Doesn't have AVX2. The stable image should still work. Please post a log file.
I bet the stable image just didn't run because you didn't map the `application.yml` correctly. Per readme it needs to be mapped differently than for native images.

**Comment by rickardfransson** [comment]
youre probably right. 
Another problem, cant pull stable.. Any ideas?
![image](https://github.com/user-attachments/assets/7d00be53-aad2-47e8-a015-a53457c4e0b3)

**Comment by Schaka** [comment]
Yes, you're not using the github repository, you're trying to pull from DockerHub. 

Refer to the readme

**Comment by rickardfransson** [comment]
Is my mapping wrong if I get this fault?

https://pastebin.pl/view/3f395847

**Comment by Schaka** [comment]
Yes, you somehow managed to break the yaml file. Your problem is not native images, so closing this ticket.
Native images will most likely continue to only support somewhat modern x86. I don't see myself building arm native images or native images for CPUs older than 10 years.

**Comment by Schaka** [comment]
The latest `develop-native` is now being built with compatibility args as well.
However, if those don't work, that's the most I'm willing to do to support older CPUs that lack AVX2 or similar instruction sets.
