### ISSUE TITLE
Mount leaving soon dir?

### ISSUE THREAD

**Issue by rickardfransson** [Schaka/janitorr#65]
Do we need to mount leaving soon dir in compose?.
beacuse im getting this fault in logs after 20seconds. Looks like I either cant connect to Emby or Janitorr doesnt see leaving soon dir.

btw, I have tried all sorts of adress to emby, like 127.0.0.1 / localhost/ and every other. No one changes the fault in logs.

Found another similar fault that was solved, the solution was to mount in compose.

Sorry for spamming issues here, but cant find another place to discuss basic things ;-)

![image](https://github.com/user-attachments/assets/93067b8e-f1b2-488c-aab8-cbb3582dcc53)

**Comment by rickardfransson** [comment]
Thanks for your answer!.

I adjusted compose and added under volymes for janitorr.
![image](https://github.com/user-attachments/assets/3629de78-ed79-49d4-81d1-d19c2ee94014)

Problem is, Im running Emby under Swizzin, and not in container. So there is no way that I know about to adjust a compose. Emby isnt running in a container.

I tried manually creating leaving-soon dir, and manually add this dir in library in emby. but that didnt help.

This is application:
![image](https://github.com/user-attachments/assets/b0dc723e-e9e4-4b1d-b748-1264d372f90c)

**Comment by Schaka** [comment]
You mapped the leaving-soon-dir inside Janitorr as /data/leaving-soon, then told Janitorr in the config file it will find it under /home/...

You need to understand that if you're mapping a directory into a container, the container only knows files and folders under the path you've given it on the right side of the mapping. So Janitorr cannot know /home/...

You really need to take 5-10 minutes out of your day to understand what volume mapping in Docker does.

If Emby isn't running through Docker, then your media-server-leaving-soon-dir pointing to the directory on the host is correct.

Your refusal to learn and expecting to be spoon fed is making me way less willing to help.

**Comment by rickardfransson** [comment]
Thank you!. You managed to explain to me so I understanded a little about filepaths in docker.
This did the trick :-)
![image](https://github.com/user-attachments/assets/18f0a80d-c6ca-4d5b-ae7d-b79fce632da8)

**Comment by Schaka** [comment]
Seeing this:
`leaving-soon-dir: /data/leaving-soon`
`media-server-leaving-soon-dir: /home/rickardfransson/Media/leaving-soon`

Without the second mapping would have worked too. I'll close this ticket. If it works for you now, that's good enough.

**Comment by rickardfransson** [comment]
Well, the dir.s is created and Janitorr finds a lot of movies and shows that match what Ive setup in config.

But, it wont create any symlinks, so the dirs is empty.

Tried to shutoff tag based deletion, found one solution here, but that didnt help.

Dont think my mappings are wrong?. Maybe a new fault?

**Comment by Schaka** [comment]
Use the mapping as suggested in my previous comment.
The symlinks will be created if mappings are correct and Janitorr can access the same files as Sonarr/Radarr and link them to a directory as explained in the readme. 

I can't **guess** what is wrong anyway. Either provide a log file with a real error (or read the log file yourself to determine if you made a mistake) or just let it be. Do not post more screenshots.

If you have a setup where symlinking isn't possible (i.e. your files are on an NFS share on a different machine), disable file access and leave it be.
