### ISSUE TITLE
Wishlist Request: Send notification when items added to Leaving Soon

### ISSUE THREAD

**Issue by hacshacdgacs** [Schaka/janitorr#67]
Definitely a wishlist item as I'm unsure of how difficult it would be to add in but is there any way to add an option to notify via a webhook or something similar (like though discord or notifiarr) of when an item has been added to/removed from the leaving soon collections. (I monitor my media server through discord with notifications so having this be able to notify me through that would also be nice)

**Comment by Schaka** [comment]
You can enable notifications in Jellyfin. If either notifiarr or discord can do that, that's what you want.

Janitorr has no control over when Jellyfin scans them and I'd like to keep it that way especially as long as the bug with library scans causing memory leaks is unresolved

**Comment by hacshacdgacs** [comment]
Emby can do the same actually, I didn't think about doing it from that
side. Thanks

**Comment by hacshacdgacs** [comment]
Hey, having moved over to jellyfin recently I can't see a way of restricting the notifications to only go off when an item is added to the leavign soon libraries. Am I missing something or is that just not an option in jellyfin? Thanks

**Comment by Schaka** [comment]
If you're using the in-browser notifications Jellyfin generates, I don't think so.
The webhook plugin is the common way people do this.

As far as I recall, you can filter for library id.
