### ISSUE TITLE
don't delete items in favorites

### ISSUE THREAD

**Issue by Snuupy** [Schaka/janitorr#69]
I see this line here https://github.com/Schaka/janitorr/blob/58fb83fad0561969e74af267ec85c31881d133ef/src/main/kotlin/com/github/schaka/janitorr/mediaserver/library/UserData.kt#L4 but I don't see it referenced anywhere in the deletion conditions nor the sample config file.

Is there any way for janitorr to not delete favorited items/seasons/shows in Jellyfin?

Thanks!

**Comment by Schaka** [comment]
No, there isn't I'm just matching the data object and mapping even the unused fields.
Having to connect items to Jellyfin first before deciding if they're immune to deletion is kind of counter-intuitive to how Janitorr is set up. It's meant to run completely without file access and just the *arrs as well. It would also be hard to recursively check all the sub-items to see if any are favorited to mark their parent as such in deletion.

I'm not sure this is something I'd want to implement.

That's what the `janitorr_keep` tag is for.

**Comment by Snuupy** [comment]
ah. I don't give my users direct access to sonarr/radarr since it is not multi user. I need to think about it too.

**Comment by Schaka** [comment]
In that case, this wouldn't work for Janitorr anyway.
The favorite flag is for the logged in user (Janitorr user set up for Jellyfin access) and not just any of your users.

Thinking about it some more, it's probably best to close this. I don't think there's a sensible way to access whether media was favorited by any user (permissions, security) and whoever can set the `janitorr_keep` tag would also be able to favorite media in Jellyfin (as Janitorr user) - so I think it's better to keep that feature centralized to the arrs.
