### ISSUE TITLE
Leaving soon adding monitored shows?

### ISSUE THREAD

**Issue by Paper319** [Schaka/janitorr#74]
Seems like there's some new shows added to leaving soon that are monitored based on the logs it says it shouldn't be doing that any reason?
`not deleting any TV shows without files or monitoring`

**Comment by Schaka** [comment]
Can you provide a proper log?
I think you're misinterpreting something here.

Janitorr looks at your entire library. It's possible you have some media in a corrupt state where it's missing files and Janitorr can't find anything to delete. This is usually stated in the logs.
