### ISSUE TITLE
Fallback to copy if symlink doesn't work

### ISSUE THREAD

**Issue by bonswouar** [Schaka/janitorr#77]
Sorry to spam you with enhancement requests😄 

I have a network share for tv shows _(and I've mounted `leaving-soon/tv` to that share, but same thing would happen if I don't)_.
I was hoping it would copy the files (as Sonarr does), but it shows the error "Couldn't find path {path}"
Would it make sense to copy files if symlinks don't work in your opinion?

P.S. Yeah I know, duplicating files for an app that's supposed to help freeing space doesn't sound amazing, but I don't see any other alternative.. I'm always open to suggestions though

**Comment by Schaka** [comment]
No, that's just the opposite of what Janitorr is trying to achieve.
You're running out of space and instead duplicating it?

No can do.

**Comment by bonswouar** [comment]
I understand!

Would it be ok to add an option to disable Leaving Soon directory somehow? To prevent creating empty folders & errors in the logs.
For example `movie-leaving-soon-enabled: true` and `tv-leaving-soon-enabled: true` or something like this

**Comment by Schaka** [comment]
Disabling Emby/Jellyfin will essentially do just that.
There is not much of a benefit to enabling them (other can potential metadata cleanup via delete requests).

I'll consider adding the option to disable leaving-soon altogether.

**Comment by bonswouar** [comment]
I meant disabling it for TV Shows only (as my network share is only for TV Shows)
But you can disregard that request, it doesn't make much sense to pollute the config for such special cases.
