### ISSUE TITLE
"Feature req" Monitor for added subtitles

### ISSUE THREAD

**Issue by rickardfransson** [Schaka/janitorr#81]
One thing that would be nice for us that doesnt have English as native language is the possibility to monitor movies for subtitles.

For ex: Dont add movie to deleting/leaving-soon before Janitorr sees a subtitle file. Maybe an integration to Bazaar could help?.
(Using bazaar for subtltiles)

Dont now if its possible, but would be a nice enhancement.

**Comment by Schaka** [comment]
https://github.com/Schaka/janitorr/issues/70

**Comment by Schaka** [comment]
No and I don't think that makes sense for Janitorr either. Not deleting something unless an external subtitle file exists is such an edge case, it doesn't fit with what I'm trying to achieve at all.

It now moves subtitles along the normal files into your leaving-soon dir.
