### ISSUE TITLE
Exclude "Favorites" in Jellyfin from deletion

### ISSUE THREAD

**Issue by yorah** [Schaka/janitorr#89]
Would be nice to allow preventing deletion of shows/movies marked as Favorite in Jellyfin.

**Comment by Schaka** [comment]
Duplicate: https://github.com/Schaka/janitorr/issues/69

**Comment by Schaka** [comment]
This is now available in the latest `:jvm-develop` tag thanks to https://github.com/Schaka/janitorr/pull/205
