### ISSUE TITLE
Leaving Soon Libraries

### ISSUE THREAD

**Issue by nothing2obvi** [Schaka/janitorr#91]
Hello, quick question. I have 3 "Leaving Soon" libraries:
- Series (Deleted Soon)
- Shows (Deleted Soon)
- Movies (Deleted Soon)

Which of the series or shows libraries can I delete? It's entirely possible I created one of them manually when I was trying to figure out how Janitorr works. Thanks!

**Comment by Schaka** [comment]
Series (Deleted Soon) is not something Janitorr creates. That was most likely you trying something out.

**Comment by nothing2obvi** [comment]
Got it, thanks!
