### ISSUE TITLE
Utilise one library for leaving soon

### ISSUE THREAD

**Issue by Brramble** [Schaka/janitorr#92]
Being able to use pre-existing libraries for leaving soon, as if you use “other films and shows” it makes duplicates.

**Comment by Schaka** [comment]
I don't understand what you're asking at all.
You can set the names in your config. If it finds the names (as you configured them), it will re-use them.

There is no way Jellyfin can put both movies and TV shows in the same library. That's not how the metadata works (reliably).

**Comment by JamsRepos** [comment]
@Schaka I think he's referring to the last option on this library:

![image](https://github.com/user-attachments/assets/816d2efb-3eb9-4d6a-a97e-4547b3822b47)

Mixed Films and Programmes which allows you to combine the two and works fine with metadata providers. 

I tested it myself, it does this. 

![image](https://github.com/user-attachments/assets/02640e7f-7a49-4874-a4c8-42c4d4411e13)


```
file-system:
  access: true
  validate-seeding: false # validates seeding by checking if the original file exists and skips deletion - turning this off will send a delete to the *arrs even if a torrent may still be active
  leaving-soon-dir: "/data/media/leaving-soon" # A directory this container can write to and Jellyfin can find under the same path - this will contain new folders with symlinks to files for Jellyfin's "Leaving Soon" collections
  media-server-leaving-soon-dir: "/data/media/leaving-soon" # This is the directory Jellyfin/Emby will be told it can find the "Leaving Soon" library, in case its mapped differently
  from-scratch: false # Clean up entire "Leaving Soon" directory and rebuild from scratch - this can help with clearing orphaned data - turning this off can save resources (less writes to drive)
  free-space-check-dir: "/data" # This is the default directory Janitorr uses to check how much space is left on your drives. By default, it checks the entire root - you may point it at a specific folder

  jellyfin:
    enabled: true
    url: "http://jellyfin:8096"
    api-key: ""
    username: username
    password: password
    delete: true # Jellyfin setup is required for JellyStat. However, if you don't want Janitorr to send delete requests to the Jellyfin API, disable it here
    leaving-soon-tv: "Leaving Soon"
    leaving-soon-movies: "Leaving Soon"

**Comment by Schaka** [comment]
Yeah, I thought he may be talking about that. It doesn't really work - the results are horrid (as in, metadata matching) you need a completely different folder structure to get anything recognized at all, etc.

If that's what he wants, I'm afraid it won't happen.

**Comment by Schaka** [comment]
Closing this because OP didn't clarify. Single library type doesn't make sense for Jellyfin's media recognition.
