### ISSUE TITLE
delete media from sonarr and radarr based on low custom score

### ISSUE THREAD

**Issue by myhme** [Schaka/janitorr#96]
if your media has low custom fomat score then delete that media. it will help in removing junk media which should be deleted first
![Screenshot 2024-11-16 130937](https://github.com/user-attachments/assets/60624ba2-3eec-40c0-9d39-165ce3ad590f)

For Example;
`Movie (2024) HDTS 1080p.mkv` having custom score 9 when i have set cutt off custom score of 10 for radarr it should be deleted.

**Comment by Schaka** [comment]
Custom score is only indicative of anything but how highly media scores for this specific release.
If you have upgrades enabled, you should always have the highest quality available.

If there's only one release available that's high quality but happens to be 1080p WEB-DL from a release group that's not necessarily known, this doesn't mean it's a release that should be deleted first.

Additionally, Janitorr does not do delete priority. It deletes in batches, so it doesn't recheck if enough space has freed up after every deletion. While this could be change (and maybe should be), I don't think this request makes sense.

**Comment by Schaka** [comment]
Correct. If you have low scoring media, the arrs should upgrade them automatically as new things get released.
I recommend setting up qbit_manage to get rid of non-hardlinked seeds.
